# Generated by Django 5.1.4 on 2025-01-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ims", "0004_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="Ims/previews",
                verbose_name="Превью",
            ),
        ),
    ]
