# Generated by Django 5.1.4 on 2025-01-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_link_to_pay_payment_session_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="link_to_pay",
            new_name="link",
        ),
    ]
